version: "3"
services:
  sentinel:
    image: aosapps/sentinel-dashboard:latest
    ports:
      - "8081:8080"
    environment:
      - USERNAME=admin
      - PASSWORD=admin
      - PROJECT_NAME=sentinel-dashboard

